codecov:
  branch: master

ignore:
    - "dbcollection/datasets"  # ignore folders and all its contents

coverage:
  status:
    project:
      default:
        target: '50'
    patch:
      default:
      target: '20'