package:
  name: dbcollection
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
  build:
    - python
    - setuptools
    - h5py
    - numpy
    - patool
    - progressbar2
    - pytest
    - scipy
    - xmltodict
    - requests
    - pillow

  run:
    - python
    - h5py
    - numpy
    - patool
    - progressbar2
    - pytest
    - scipy
    - xmltodict
    - requests
    - pillow

test:
  imports:
    - dbcollection

about:
  home: https://github.com/dbcollection/dbcollection
  license: MIT