package:
  name: dbcollection
  version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

source:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
  {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - h5py
    - numpy
    - patool
    - progressbar2
    - pytest
    - scipy
    - xmltodict
    - requests
    - pillow

  run:
    - python
    - h5py
    - numpy
    - patool
    - progressbar2
    - pytest
    - scipy
    - xmltodict
    - requests
    - pillow

test:
  imports:
    - dbcollection

about:
  home: https://github.com/farrajota/dbcollection
  license: MIT